Added support for plugin diagnostics
intelsdi-x/snap-plugin-lib-py pull request #21
Opened 2017-07-04 09:53 UTC by kdembler

Added diagnostic mode to lib.
If plugin is run without config from framework present, it will start in diagnostic mode.
Plugin authors also have an option to add flags, so they can change behaviour of the plugin based on presence/value of CLI args.

TODO:

- [ ] Add tests
- [ ] Add documentation to README

2017-07-05 08:26 UTC, PatrykMatyjasek requested changes

2017-07-05 08:26 UTC, PatrykMatyjasek commented on snap_plugin/v1/metric.py
>                              "aceElement.  (given: `{}`)"
redundant comment

2017-07-05 08:26 UTC, PatrykMatyjasek commented on snap_plugin/v1/metric.py
> +        self._set_config(config)
called method raises error, we should handle it

2017-07-05 08:26 UTC, PatrykMatyjasek commented on snap_plugin/v1/plugin.py
> +            self._print_diagnostic()
missing else

2017-07-05 08:47 UTC, kdembler commented on snap_plugin/v1/plugin.py
> +            self._print_diagnostic()
Fixed in 2a3ced9

2017-07-05 08:50 UTC, kdembler commented on snap_plugin/v1/metric.py
> +        self._set_config(config)
Error should be unhandled, as it should be passed to user's scope to let him know he called constructor with wrong args. Added docstring info about errors raised in 2a3ced9 for better readability.

2017-07-06 14:36 UTC, PatrykMatyjasek approved these changes

2017-07-06 14:36 UTC, PatrykMatyjasek commented
Please squash commits
LGTM

2017-07-06 14:38 UTC, kdembler commented
@PatrykMatyjasek Squashed :+1:

2017-07-06 14:42 UTC, merged